name: Node.js CI/CD Message Queue

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        # 1. Trỏ vào file lock của Message-queue
        cache-dependency-path: message-queue/package-lock.json

    - run: npm ci
      # 2. Chạy lệnh cài đặt bên trong thư mục Message-queue
      working-directory: ./message-queue
